---
title: "External Data Sources and Simple Distributions"
author: "Daniel Redwine"
output: 
  html_document:
    toc: true # table of content true
    toc_depth: 2  # up to one depth of headings, no subheader (specified by # in html)
    number_sections: false  ## if you want number sections at each table header
    theme: united  # many options for theme
---
```{r setup, echo=FALSE, warning=FALSE, include = FALSE, message=FALSE}
packages<-c("cowplot","dismo","leaflet","mapdata","OpenStreetMap","rasterVis","rdryad","rgbif","sf","tidyverse")
sapply(packages, library, character.only=T)
```
# GitHub Datasets
```{r retrieve kml github, message=FALSE, results='hide', warning=FALSE, echo=FALSE}
campus.kml <- st_read('https://raw.githubusercontent.com/chrismgentry/Mapping-Basics/master/Data/Campus_Points.kml') # Load in the dataset directly from GitHub

campus_outline <- st_read("https://raw.githubusercontent.com/chrismgentry/Mapping-Basics/master/Data/Main_Campus.kml") # Load in the polygon dataset from Github

```

```{r campus kml, echo=FALSE, warning=FALSE, message=FALSE, fig.show = "hold", out.width = "100%", fig.align = "center", fig.cap="Figure 1. Map of the APSU main campus. Buildings are plotted as points within the main campus outlined red. Data obtained via github.com/chrismgentry/Mapping-Basics"}

# Create the campus points data frame with x and y from the KML geometry
campus.points <- campus.kml %>% mutate(x = unlist(map(campus.kml$geometry,1)),
                                       y = unlist(map(campus.kml$geometry,2))) %>%
                                st_drop_geometry(campus.kml)

# Create the main campus polygon
campus_poly <- cbind.data.frame(st_coordinates(campus_outline)[,1],
                                 st_coordinates(campus_outline)[,2],
                                 st_coordinates(campus_outline)[,3],
                                 st_coordinates(campus_outline)[,4])

# Name columns
colnames(campus_poly) <- c("X","Y", "id", "group")

# Retrieve the base map with openmap
campus.base <- openmap(c(36.5360,-87.3570),c(36.5300,-87.3495), type='esri-topo')

# Project latitude and longitude in the correct form onto the base map
APSU <- openproj(campus.base, projection = "+proj=longlat +ellps=WGS84 +units=m +no_defs")

# Plotting points, polygon, and adding aesthetics 
apsu_map <- autoplot.OpenStreetMap(APSU) +
  geom_polygon(data=campus_poly, aes(x = X, y = Y), alpha = .1, size = 1, color="red") +
  geom_point(data=campus.points, aes(x = x, y = y, color = Name), size = 3, alpha = 1) +
  geom_text(data=campus.points,aes(x = x, y = y, label = Name), color="black", vjust=-0.8, size = 2.5, fontface="bold", check_overlap = FALSE) +
  labs(x="Longtiude", y="Latitude") + theme(legend.position = "none")

#state <- map_data("state") # Retrieve state lines
county <- map_data("county") # Retrieve county lines
apsu_point <- data.frame("x" = -87.353069, "y" = 36.533654) # location of APSU

tn <- county %>% 
  filter(region=="tennessee") # Only counties for Tennessee

montco <- county %>% # Define Montgomery County
  filter(region=="tennessee") %>% 
  filter(subregion=="montgomery")

inset <- ggplot() + #geom_polygon(data = state, aes(x=long, y = lat, group = group),
                       # fill = "ivory", color="black") + 
           geom_polygon(data = tn, aes(x=long, y = lat, group = group),
                        fill = "gray", color="black") +
           geom_polygon(data = montco, aes(x=long, y = lat, group = group),
                        fill = "red", color="black")+ 
           geom_point(data = apsu_point, aes(x=x,y=y), color="black") +
  coord_fixed(xlim = c(-91, -81),  ylim = c(34, 37), ratio = 1.2) + 
    theme(plot.background = element_rect(fill='transparent', color=NA),
panel.background = element_rect(fill='transparent', color = NA), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
        axis.line=element_blank(), axis.text.x=element_blank(), axis.text.y=element_blank(),axis.ticks=element_blank(), 
        axis.title.x=element_blank(), axis.title.y=element_blank()) +
  theme(plot.margin=grid::unit(c(0,0,0,0), "mm"))

ggdraw() +
  draw_plot(apsu_map) + 
  draw_plot(inset, x = 0.55, y = 0.0, width = 0.4, height = 0.4,)
```
# GBIF Datasets

## *DISMO*

```{r DISMO mapcode, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE, results='hide'}

# Obtain the dataset from GBIF using gbif(). removeZeros removes entries with zeros
henslow.dismo <- gbif("ammodramus", species = "henslowii", ext = c(-91,-81,30,40),
                   geo = TRUE, download = TRUE, removeZeros = TRUE)

us <- map_data("state")

henslow_map <- ggplot() +
  geom_polygon(data = us, aes(x=long, y = lat, group = group),
               fill = "lightgreen", color="black") +
  geom_point(data = henslow.dismo, aes(x=lon, y=lat), color = "black", size = 2) + 
  xlab("Longitude") + ylab("Latitude") +
  coord_fixed(xlim = c(-91,-81), ylim = c(30,40)) +
  xlab("Longitude") + ylab("Latitude") + 
  theme_bw() + theme(plot.title = element_text(hjust = 0.5)) + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "lightblue"))
```
```{r DISMO map, echo=FALSE, warning=FALSE, message=FALSE, fig.show = "hold", out.width = "100%", fig.align = "center", fig.cap="Figure 2. Distribution of Henslow's Sparrows in the southeastern United States obtained via DISMO from the GBIF dataset."}

henslow_map
```

## *RGBIF*

```{r RGBIF data static map, echo=FALSE, warning=FALSE, message=FALSE, fig.show = "hold", out.width = "100%", fig.align = "center", fig.cap="Figure 3. Distribution of Henslow's Sparrows and Grasshopper Sparrows in the southeastern United States obtained via RGBIF from the GBIF dataset."}

# Retrieve data with rgbif for Henslow's
henslow.rgbif <- occ_data(scientificName = "Ammodramus henslowii",
                       hasCoordinate = TRUE, limit = 2000,
                       decimalLongitude = "-91, -81", 
                       decimalLatitude = "30, 40")

# Retrieve data with rgbif for GRSP
grsp.rgbif <- occ_data(scientificName = "Ammodramus savannarum",
                       hasCoordinate = TRUE, limit = 2000,
                       decimalLongitude = "-91, -81", 
                       decimalLatitude = "30, 40")

# RGBIF data does not come in a form suitable for ggplot
# Data must be converted to a dataframe using cbind
# Create Henslow's dataframe
henslow.rgbif.df <- cbind.data.frame(henslow.rgbif$data$species,
                                  henslow.rgbif$data$decimalLatitude,
                                  henslow.rgbif$data$decimalLongitude,
                                  henslow.rgbif$data$stateProvince,
                                  henslow.rgbif$data$verbatimLocality)

# Create GRSP dataframe 
grsp.rgbif.df <- cbind.data.frame(grsp.rgbif$data$species,
                                  grsp.rgbif$data$decimalLatitude,
                                  grsp.rgbif$data$decimalLongitude,
                                  grsp.rgbif$data$stateProvince,
                                  grsp.rgbif$data$verbatimLocality,
                                  grsp.rgbif$data$month)

# Rename the columns
colnames(henslow.rgbif.df) <- c("species","y","x","state","location")
colnames(grsp.rgbif.df) <- c("species","y","x","state","location","month")

# Plot both Henslow's and GRSP 
ggplot() +
  geom_polygon(data = us, aes(x=long, y = lat, group = group),
               fill = "floralwhite", color="black") +
  geom_point(data = grsp.rgbif.df, aes(x=x, y=y, color = species), size = 2) +
  geom_point(data = henslow.rgbif.df, aes(x=x, y=y, color = species), size = 2) + 
  coord_fixed(xlim = c(-91,-81), ylim = c(30,40)) +
  xlab("Longitude") + ylab("Latitude") +  
  guides(color=guide_legend("Legend", override.aes = list(size = 4))) +
  theme_bw() + theme(plot.title = element_text(hjust = 0.5)) + 
  theme(legend.position = "bottom") +
  theme(legend.title = element_blank(), legend.box.just = "center") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "lightblue"))
```
```{r RGBIF data interactive map, echo=FALSE, warning=FALSE, message=FALSE, fig.show = "hold", out.width = "100%", fig.align = "center", fig.cap="Figure 4. Distribution of Grasshopper Sparrows in Tennessee and surrounding states obtained via RGBIF from the GBIF dataset."}


leaflet(grsp.rgbif.df) %>% 
  setView(lat = 35.5175, lng = -86.5804, zoom = 7) %>%
  addTiles() %>% 
  addCircleMarkers(grsp.rgbif.df$x,
                   grsp.rgbif.df$y,
                   popup = grsp.rgbif.df$month,
                   radius = 4,
                   weight = 1,
                   color = "blue",
                   fillColor = "blue",
                   fillOpacity = 0.4) %>%
  addMiniMap(position = 'topright',
             width = 100, 
             height = 100,
             toggleDisplay = FALSE) %>%
  addScaleBar(position = "bottomright")

```

# Distribution Model

```{r Dryad data map, echo=FALSE, warning=FALSE, message=FALSE, fig.show = "hold", out.width = "100%", fig.align = "center", fig.cap="Figure 5. Probability of Grasshopper Sparrow occurrencce modelled on climactic variables obtained via worldclim.org."}
bioclim <- getData(name = "worldclim", res = 2.5, var = "bio", path = "./")

names(bioclim) <- c("Ann Mean Temp","Mean Diurnal Range","Isothermality","Temperature Seasonality",
                    "Max Temp Warmest Mo","Min Temp Coldest Mo","Ann Temp Range","Mean Temp Wettest Qtr",
                    "Mean Temp Driest Qtr","Mean Temp Warmest Qtr","Mean Temp Coldest Qtr","Annual
                    Precip","Precip Wettest Mo","Precip Driest Mo","Precip Seasonality","Precip Wettest
                    Qtr","Precip Driest Qtr","Precip Warmest Qtr","Precip Coldest Qtr")

bio.extent <- extent(x = c(
  min(grsp.rgbif.df$x),
  max(grsp.rgbif.df$x),
  min(grsp.rgbif.df$y),
  max(grsp.rgbif.df$y)))

bioclim.extent <- crop(x = bioclim, y = bio.extent)

bioclim.model <- bioclim(x = bioclim.extent, p = cbind(grsp.rgbif.df$x,grsp.rgbif.df$y))
presence.model <- dismo::predict(object = bioclim.model, 
                                 x = bioclim.extent, 
                                 ext = bio.extent)

rasterVis::gplot(presence.model) + 
  geom_polygon(data = us, aes(x= long, y = lat, group = group),
               fill = "gray", color="black") +
  geom_raster(aes(fill=value)) +
  geom_polygon(data = us, aes(x= long, y = lat, group = group),
               fill = NA, color="black") +
  geom_point(data = grsp.rgbif.df, aes(x = x, y = y), size = 2, color = "black", alpha = 0.5) +
  scale_fill_gradientn(colours=c("palegreen1","deepskyblue2","ghostwhite"), "Probability") +
  coord_fixed(xlim = c(-90,-82), ylim = c(31,39)) +
  xlab("Longitude") + ylab("Latitude") + 
  theme_bw() + theme(plot.title = element_text(hjust = 0.5)) + theme(legend.position = "right") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "lightblue"))

```

