---
title: "External Data Sources and Simple Distributions"
author: "Daniel Redwine"
output: 
  html_document:
    toc: true # table of content true
    toc_depth: 2  # up to one depth of headings, no subheader (specified by # in html)
    number_sections: false  ## if you want number sections at each table header
    theme: united  # many options for theme
---
```{r setup, echo=FALSE, warning=FALSE, include = FALSE}
packages<-c("cowplot","dismo","leaflet","mapdata","OpenStreetMap","rasterVis","rdryad","rgbif","sf","tidyverse")
sapply(packages, library, character.only=T)
```
# Introduction

The way that KML data is put together you can fairly easily access the data using st read to get point data. Works the same way as a local file, just the directory isn't on your computer. Tennessee GIS has data that you can download such as river systems or watersheds. While the link on the site is broken, the data is still accessible on the Google drive.

# Connecting to Data Distribution Networks

## DISMO

Remember, data is always longitude first, then lattitiude. For GBIF you must download or else it will only display the data and not allow it to be stored as an object. Use map_data() to get data such as states etc. When you have polygons for a single data point you have to have multiple x and y. Polygons are drawn from one point to the next and must be grouped in order for each individual polygon to be distinct. Remember when using open data source there may not be quality control. 

## RGBIF

Consider the level of data you need to complete a project or research. IN RGBIF you have to tell it how many records to return, including those which are incomplete records. Decimal longitude and decimal latitiude function as the extent in theis case. The data does not originate as a data frame, it is structured as a large gbif table dataframe which contains different structured classes. You can map data straight from RGBIF, but it must be first put into a dtaframe if you want to use ggplot. To get into dataframe form you may have to dig into the data and determine how to create the dataframe. Pay close attention and know what you're mapping as there is less quality control with data that is not yours. 

## Dryad

You can access data directly from dryad datasets. You can use dryad.download or download.file. Include mode = "wb" for the correct data streaming. You can create an insert map using cowplot. You can then put the main map and the inset map together using ggplot. Remember that the last plot added is the top layer. 

## Simple Species Distribution Map

When working with spatial data you can use the dataframe to set the extent. When creating distribution maps using raster data you can use gplot instead of ggplot. 